services:
  scoring-api:
    build: .
    container_name: credit-scoring-api
    ports:
      - "8000:8000"
    volumes:
      # Mount models folder so the container can see the trained model
      - ./models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    restart: always